name: CD - Deploy to AWS

on:
  push:
    branches: [ dev ]

  workflow_dispatch:

env:
  NODE_VERSION: '14.x'
  REGION: 'us-west-1'
  AWS_S3_NAME: 'test-nextjs'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run coverage --if-present
          npm run lint

  deploy:
    name: Deployment
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn export

      - name: Configure AWS Credentials & Deploy 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }} 
      - name: deploy
        run: aws s3 sync ./out s3://${{ env.AWS_S3_NAME }}